Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Anaconda\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Anaconda\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Anaconda\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Anaconda\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Anaconda\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Anaconda\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Anaconda\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Now we generate a unique DataFrame with the BBVA office address
for page in range(0,len(BBVA)):
    n_var = len(BBVA[page].columns)
    if page == 0:
        BBVA[page].columns = BBVA[page].iloc[0]
        column_names = BBVA[page].columns
        BBVA[page] = BBVA[page].drop(BBVA[page].index[0])
        bbva_offices = BBVA[page]
        bbva_offices.reset_index()
    elif n_var == 6:
        BBVA[page] = BBVA[page].drop('Unnamed: 0', axis=1)
        row = list(BBVA[page].columns)
        BBVA[page].loc[len(BBVA[page])] = row
        BBVA[page].columns = column_names
        last_row = BBVA[page].iloc[-1]
        BBVA[page] = BBVA[page].iloc[0:-1]
        BBVA[page] = pd.concat([last_row.to_frame().T, BBVA[page]], ignore_index=True)
        bbva_offices = pd.concat([BBVA[page], bbva_offices])
        bbva_offices.reset_index()
    else:
        row = list(BBVA[page].columns)
        BBVA[page].loc[len(BBVA[page])] = row
        BBVA[page].columns = column_names
        last_row = BBVA[page].iloc[-1]
        BBVA[page] = BBVA[page].iloc[0:-1]
        BBVA[page] = pd.concat([last_row.to_frame().T, BBVA[page]], ignore_index=True)
        bbva_offices = pd.concat([BBVA[page], bbva_offices])
        bbva_offices.reset_index()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mValueError[0m                                Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_8092\3488879711.py[0m in [0;36m<module>[1;34m[0m
[0;32m     21[0m         [0mrow[0m [1;33m=[0m [0mlist[0m[1;33m([0m[0mBBVA[0m[1;33m[[0m[0mpage[0m[1;33m][0m[1;33m.[0m[0mcolumns[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     22[0m         [0mBBVA[0m[1;33m[[0m[0mpage[0m[1;33m][0m[1;33m.[0m[0mloc[0m[1;33m[[0m[0mlen[0m[1;33m([0m[0mBBVA[0m[1;33m[[0m[0mpage[0m[1;33m][0m[1;33m)[0m[1;33m][0m [1;33m=[0m [0mrow[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 23[1;33m         [0mBBVA[0m[1;33m[[0m[0mpage[0m[1;33m][0m[1;33m.[0m[0mcolumns[0m [1;33m=[0m [0mcolumn_names[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     24[0m         [0mlast_row[0m [1;33m=[0m [0mBBVA[0m[1;33m[[0m[0mpage[0m[1;33m][0m[1;33m.[0m[0miloc[0m[1;33m[[0m[1;33m-[0m[1;36m1[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[0;32m     25[0m         [0mBBVA[0m[1;33m[[0m[0mpage[0m[1;33m][0m [1;33m=[0m [0mBBVA[0m[1;33m[[0m[0mpage[0m[1;33m][0m[1;33m.[0m[0miloc[0m[1;33m[[0m[1;36m0[0m[1;33m:[0m[1;33m-[0m[1;36m1[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\Anaconda\lib\site-packages\pandas\core\generic.py[0m in [0;36m__setattr__[1;34m(self, name, value)[0m
[0;32m   5586[0m         [1;32mtry[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m   5587[0m             [0mobject[0m[1;33m.[0m[0m__getattribute__[0m[1;33m([0m[0mself[0m[1;33m,[0m [0mname[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 5588[1;33m             [1;32mreturn[0m [0mobject[0m[1;33m.[0m[0m__setattr__[0m[1;33m([0m[0mself[0m[1;33m,[0m [0mname[0m[1;33m,[0m [0mvalue[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   5589[0m         [1;32mexcept[0m [0mAttributeError[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m   5590[0m             [1;32mpass[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\Anaconda\lib\site-packages\pandas\_libs\properties.pyx[0m in [0;36mpandas._libs.properties.AxisProperty.__set__[1;34m()[0m

[1;32mC:\Anaconda\lib\site-packages\pandas\core\generic.py[0m in [0;36m_set_axis[1;34m(self, axis, labels)[0m
[0;32m    767[0m     [1;32mdef[0m [0m_set_axis[0m[1;33m([0m[0mself[0m[1;33m,[0m [0maxis[0m[1;33m:[0m [0mint[0m[1;33m,[0m [0mlabels[0m[1;33m:[0m [0mIndex[0m[1;33m)[0m [1;33m->[0m [1;32mNone[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    768[0m         [0mlabels[0m [1;33m=[0m [0mensure_index[0m[1;33m([0m[0mlabels[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 769[1;33m         [0mself[0m[1;33m.[0m[0m_mgr[0m[1;33m.[0m[0mset_axis[0m[1;33m([0m[0maxis[0m[1;33m,[0m [0mlabels[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    770[0m         [0mself[0m[1;33m.[0m[0m_clear_item_cache[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    771[0m [1;33m[0m[0m

[1;32mC:\Anaconda\lib\site-packages\pandas\core\internals\managers.py[0m in [0;36mset_axis[1;34m(self, axis, new_labels)[0m
[0;32m    212[0m     [1;32mdef[0m [0mset_axis[0m[1;33m([0m[0mself[0m[1;33m,[0m [0maxis[0m[1;33m:[0m [0mint[0m[1;33m,[0m [0mnew_labels[0m[1;33m:[0m [0mIndex[0m[1;33m)[0m [1;33m->[0m [1;32mNone[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    213[0m         [1;31m# Caller is responsible for ensuring we have an Index object.[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 214[1;33m         [0mself[0m[1;33m.[0m[0m_validate_set_axis[0m[1;33m([0m[0maxis[0m[1;33m,[0m [0mnew_labels[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    215[0m         [0mself[0m[1;33m.[0m[0maxes[0m[1;33m[[0m[0maxis[0m[1;33m][0m [1;33m=[0m [0mnew_labels[0m[1;33m[0m[1;33m[0m[0m
[0;32m    216[0m [1;33m[0m[0m

[1;32mC:\Anaconda\lib\site-packages\pandas\core\internals\base.py[0m in [0;36m_validate_set_axis[1;34m(self, axis, new_labels)[0m
[0;32m     67[0m [1;33m[0m[0m
[0;32m     68[0m         [1;32melif[0m [0mnew_len[0m [1;33m!=[0m [0mold_len[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 69[1;33m             raise ValueError(
[0m[0;32m     70[0m                 [1;34mf"Length mismatch: Expected axis has {old_len} elements, new "[0m[1;33m[0m[1;33m[0m[0m
[0;32m     71[0m                 [1;34mf"values have {new_len} elements"[0m[1;33m[0m[1;33m[0m[0m

[1;31mValueError[0m: Length mismatch: Expected axis has 3 elements, new values have 6 elements
ValueError: Length mismatch: Expected axis has 3 elements, new values have 6 elements

